#requires -version 5.1
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$Runtime=Join-Path $Root 'Runtime';$LocaleDir=Join-Path $Root 'Locales';$ProfilePath=Join-Path $Root 'Profiles\legacy_profiles.json'
$Profiles=Get-Content $ProfilePath -Raw -Encoding UTF8|ConvertFrom-Json
$SettingsPath=Join-Path $Root 'lifeline_settings.json';$LogDir=Join-Path $Root 'Logs';New-Item -ItemType Directory -Force -Path $LogDir|Out-Null
$Log=Join-Path $LogDir ('Lifeline-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'.log')
$script:Strings=@{};$script:Bindings=@{};$script:Locale='en-US'
function Log([string]$m){Add-Content -LiteralPath $Log -Encoding UTF8 -Value ((Get-Date -Format 's')+' '+$m)}
function ReadJson($p){try{Get-Content $p -Raw -Encoding UTF8|ConvertFrom-Json}catch{$null}}
function LoadLocale([string]$code){$fallback=ReadJson (Join-Path $LocaleDir 'en-US.json');$target=ReadJson (Join-Path $LocaleDir ($code+'.json'));$h=@{};$fallback.psobject.Properties|%{$h[$_.Name]=[string]$_.Value};if($target){$target.psobject.Properties|%{$h[$_.Name]=[string]$_.Value}};$script:Strings=$h;$script:Locale=$code}
function T([string]$k){if($script:Strings.ContainsKey($k)){return $script:Strings[$k]}return $k}
function Bind($c,[string]$k){if(!$script:Bindings.ContainsKey($k)){$script:Bindings[$k]=@()};$script:Bindings[$k]+=@($c);$c.Text=T $k}
function SaveSettings{[pscustomobject]@{locale=$script:Locale}|ConvertTo-Json|Set-Content $SettingsPath -Encoding UTF8}
$s=ReadJson $SettingsPath;if($s -and $s.locale){LoadLocale $s.locale}else{LoadLocale 'en-US'}
function GpuInfo{try{$g=Get-CimInstance Win32_VideoController|Select-Object -First 1 Name,AdapterRAM,DriverVersion;$v=if($g.AdapterRAM){[math]::Round($g.AdapterRAM/1GB,1)}else{0};[pscustomobject]@{Name=$g.Name;VRAM=$v;Driver=$g.DriverVersion}}catch{[pscustomobject]@{Name='Unknown';VRAM=0;Driver='Unknown'}}}
function Tier($name){foreach($t in $Profiles.tiers){foreach($m in $t.match){if($name -like ('*'+$m+'*')){return $t}}};return ($Profiles.tiers|? id -eq 'OTHER')}
function SetIni($path,$sec,$key,$val){if(!(Test-Path $path)){return};$a=[Collections.Generic.List[string]](Get-Content $path);$s='['+$sec+']';$si=-1;$next=$a.Count;for($i=0;$i-lt$a.Count;$i++){if($a[$i].Trim()-ieq$s){$si=$i;break}};if($si-lt0){$a.Add('');$a.Add($s);$a.Add($key+'='+$val);Set-Content $path $a -Encoding UTF8;return};for($i=$si+1;$i-lt$a.Count;$i++){if($a[$i]-match '^\s*\['){$next=$i;break}};for($i=$si+1;$i-lt$next;$i++){if($a[$i]-match ('^\s*'+[regex]::Escape($key)+'\s*=')){$a[$i]=$key+'='+$val;Set-Content $path $a -Encoding UTF8;return}};$a.Insert($next,$key+'='+$val);Set-Content $path $a -Encoding UTF8}
function AntiCheat($folder){foreach($m in @('EasyAntiCheat','BattlEye','vgk','xigncode','nProtect')){if(Get-ChildItem $folder -Recurse -Depth 4 -Force -ErrorAction SilentlyContinue|? Name -like ('*'+$m+'*')|Select-Object -First 1){return $true}}return $false}
function Validate402($file){if(!(Test-Path $file)){return [pscustomobject]@{Ok=$false;Why=(T 'fsr402_missing')}};if($file -match '(?i)4\.0\.2c|402c'){return [pscustomobject]@{Ok=$false;Why=(T 'fsr402_blocked')}};$v=(Get-Item $file).VersionInfo.FileVersion;if($v -and $v -notmatch '^4\.0\.2'){return [pscustomobject]@{Ok=$false;Why=('Version is not 4.0.2: '+$v)}};$sig=Get-AuthenticodeSignature $file;$hash=(Get-FileHash $file -Algorithm SHA256).Hash;return [pscustomobject]@{Ok=$true;Why=('4.0.2 candidate; signature='+$sig.Status+'; version='+$v+'; sha256='+$hash)}}
function CopyBaseline($folder,$hook){$backup=Join-Path $folder ('.AetherScaler_Lifeline_Backup\'+(Get-Date -Format 'yyyyMMdd-HHmmss'));New-Item -ItemType Directory -Force -Path $backup|Out-Null;$names=@($hook,'OptiScaler.ini','amd_fidelityfx_dx12.dll','amd_fidelityfx_upscaler_dx12.dll','amd_fidelityfx_framegeneration_dx12.dll','fakenvapi.dll','fakenvapi.ini','libxess.dll','libxess_fg.dll','libxell.dll');foreach($n in $names){if(Test-Path (Join-Path $folder $n)){Copy-Item (Join-Path $folder $n) $backup -Force}};Copy-Item (Join-Path $Runtime 'OptiScaler.dll') (Join-Path $folder $hook) -Force;$ini=Join-Path $folder 'OptiScaler.ini';if(!(Test-Path $ini)){Copy-Item (Join-Path $Runtime 'OptiScaler.ini.template') $ini -Force};foreach($n in @('amd_fidelityfx_dx12.dll','amd_fidelityfx_upscaler_dx12.dll','amd_fidelityfx_framegeneration_dx12.dll','amd_fidelityfx_vk.dll','fakenvapi.dll','fakenvapi.ini','libxess.dll','libxess_dx11.dll','libxess_fg.dll','libxell.dll','dlssg_to_fsr3_amd_is_better.dll')){if(Test-Path (Join-Path $Runtime $n)){Copy-Item (Join-Path $Runtime $n) $folder -Force}};return [pscustomobject]@{Ini=$ini;Backup=$backup}}
function Restore($folder){$r=Join-Path $folder '.AetherScaler_Lifeline_Backup';if(!(Test-Path $r)){return $false};$last=Get-ChildItem $r -Directory|Sort-Object Name -Descending|Select-Object -First 1;if(!$last){return $false};Get-ChildItem $last.FullName -File|%{Copy-Item $_.FullName (Join-Path $folder $_.Name) -Force};return $true}
function FontForLocale([string]$l){$c=@{'zh-TW'='C:\Windows\Fonts\msjh.ttc';'ja-JP'='C:\Windows\Fonts\YuGothM.ttc';'ko-KR'='C:\Windows\Fonts\malgun.ttf';'en-US'='C:\Windows\Fonts\segoeui.ttf';'de-DE'='C:\Windows\Fonts\segoeui.ttf';'fr-FR'='C:\Windows\Fonts\segoeui.ttf';'es-ES'='C:\Windows\Fonts\segoeui.ttf';'pt-BR'='C:\Windows\Fonts\segoeui.ttf'};$p=$c[$l];if($p -and (Test-Path $p)){return $p};return $null}
$gpu=GpuInfo;$tier=Tier $gpu.Name
function Recommendation{ $f=[int]$numFps.Value;$strategy=$cmbStrategy.SelectedIndex;$u=[string]$tier.primary;$fgout='nofg';if($strategy -eq 2 -and $f -ge 40 -and $tier.fg -ne 'off'){$fgout=[string]$tier.fg}elseif($strategy -eq 0 -and $f -ge [int]$tier.min_fg_fps -and $tier.fg -ne 'off'){$fgout=[string]$tier.fg};if($strategy -eq 1 -or $f -lt 30){$fgout='nofg'};return [pscustomobject]@{Upscaler=$u;FG=$fgout}}
function RefreshRecommendation{$r=Recommendation;$lblRec.Text=(T 'recommendation')+': '+$r.Upscaler+' + '+$(if($r.FG-eq'nofg'){T 'off'}else{$r.FG});$f=[int]$numFps.Value;if($f-lt30){$lblWarn.Text=T 'fg_blocked'}elseif($f-lt40){$lblWarn.Text=T 'fg_low'}elseif($f-lt[int]$tier.min_fg_fps){$lblWarn.Text=T 'fg_experimental'}else{$lblWarn.Text=T 'fg_ok'};if($gpu.VRAM-lt6){$lblWarn.Text+='  '+(T 'vram_warning')}}
function ApplyLanguage{$code=$localeCodes[$cmbLanguage.SelectedIndex];LoadLocale $code;foreach($k in @($script:Bindings.Keys)){foreach($c in @($script:Bindings[$k])){$c.Text=T $k}};$form.Text=T 'app_title';$tabPlay.Text=T 'tab_play';$tabAdv.Text=T 'tab_advanced';$tabSupport.Text=T 'tab_support';$cmbStrategy.Items.Clear();[void]$cmbStrategy.Items.AddRange(@((T 'recommended'),(T 'low_latency'),(T 'max_fps')));$cmbStrategy.SelectedIndex=0;$cmbFG.Items.Clear();[void]$cmbFG.Items.AddRange(@((T 'auto'),(T 'off'),'fsrfg','xefg'));$cmbFG.SelectedIndex=0;SaveSettings;RefreshRecommendation}
$form=New-Object Windows.Forms.Form;$form.Text=T 'app_title';$form.Size='880,690';$form.StartPosition='CenterScreen';$form.MinimumSize='880,690'
$localeCodes=@('en-US','zh-TW','ja-JP','ko-KR','de-DE','fr-FR','es-ES','pt-BR');$localeNames=@();foreach($c in $localeCodes){$j=ReadJson (Join-Path $LocaleDir ($c+'.json'));$localeNames+=$j.language_name}
$lblLang=New-Object Windows.Forms.Label;$lblLang.Location='575,16';$lblLang.AutoSize=$true;Bind $lblLang 'language';$form.Controls.Add($lblLang)
$cmbLanguage=New-Object Windows.Forms.ComboBox;$cmbLanguage.Location='640,12';$cmbLanguage.Width=205;$cmbLanguage.DropDownStyle='DropDownList';[void]$cmbLanguage.Items.AddRange($localeNames);$idx=[array]::IndexOf($localeCodes,$script:Locale);$cmbLanguage.SelectedIndex=$(if($idx-ge0){$idx}else{0});$form.Controls.Add($cmbLanguage)
$tabs=New-Object Windows.Forms.TabControl;$tabs.Location='15,48';$tabs.Size='830,555';$form.Controls.Add($tabs)
$tabPlay=New-Object Windows.Forms.TabPage;$tabPlay.Text=T 'tab_play';$tabs.TabPages.Add($tabPlay)
$tabAdv=New-Object Windows.Forms.TabPage;$tabAdv.Text=T 'tab_advanced';$tabs.TabPages.Add($tabAdv)
$tabSupport=New-Object Windows.Forms.TabPage;$tabSupport.Text=T 'tab_support';$tabs.TabPages.Add($tabSupport)
function Label($parent,$x,$y,$key){$o=New-Object Windows.Forms.Label;$o.Location="$x,$y";$o.AutoSize=$true;Bind $o $key;$parent.Controls.Add($o);return $o}
Label $tabPlay 20 20 'game_folder'|Out-Null;$txtFolder=New-Object Windows.Forms.TextBox;$txtFolder.Location='20,45';$txtFolder.Width=620;$tabPlay.Controls.Add($txtFolder);$btnBrowse=New-Object Windows.Forms.Button;$btnBrowse.Location='655,43';$btnBrowse.Size='130,28';Bind $btnBrowse 'browse';$tabPlay.Controls.Add($btnBrowse)
$lblGpu=New-Object Windows.Forms.Label;$lblGpu.Location='20,90';$lblGpu.Size='765,45';$lblGpu.Text=(T 'detected_gpu')+': '+$gpu.Name+' | VRAM '+$gpu.VRAM+' GB | '+(T 'tier')+': '+$tier.label;$tabPlay.Controls.Add($lblGpu)
Label $tabPlay 20 150 'base_fps'|Out-Null;$numFps=New-Object Windows.Forms.NumericUpDown;$numFps.Location='20,175';$numFps.Minimum=1;$numFps.Maximum=300;$numFps.Value=45;$tabPlay.Controls.Add($numFps)
Label $tabPlay 250 150 'strategy'|Out-Null;$cmbStrategy=New-Object Windows.Forms.ComboBox;$cmbStrategy.Location='250,175';$cmbStrategy.Width=220;$cmbStrategy.DropDownStyle='DropDownList';[void]$cmbStrategy.Items.AddRange(@((T 'recommended'),(T 'low_latency'),(T 'max_fps')));$cmbStrategy.SelectedIndex=0;$tabPlay.Controls.Add($cmbStrategy)
$lblRec=New-Object Windows.Forms.Label;$lblRec.Location='20,225';$lblRec.Size='765,30';$tabPlay.Controls.Add($lblRec);$lblWarn=New-Object Windows.Forms.Label;$lblWarn.Location='20,260';$lblWarn.Size='765,60';$lblWarn.ForeColor=[Drawing.Color]::DarkOrange;$tabPlay.Controls.Add($lblWarn)
$btnApply=New-Object Windows.Forms.Button;$btnApply.Location='20,350';$btnApply.Size='250,60';Bind $btnApply 'apply';$tabPlay.Controls.Add($btnApply);$btnRestore=New-Object Windows.Forms.Button;$btnRestore.Location='290,350';$btnRestore.Size='230,60';Bind $btnRestore 'restore';$tabPlay.Controls.Add($btnRestore);$btnSupportQuick=New-Object Windows.Forms.Button;$btnSupportQuick.Location='540,350';$btnSupportQuick.Size='245,60';Bind $btnSupportQuick 'export_support';$tabPlay.Controls.Add($btnSupportQuick)
Label $tabAdv 20 20 'advanced_warning'|Out-Null;Label $tabAdv 20 65 'upscaler'|Out-Null;$cmbUpscaler=New-Object Windows.Forms.ComboBox;$cmbUpscaler.Location='20,90';$cmbUpscaler.Width=220;$cmbUpscaler.DropDownStyle='DropDownList';[void]$cmbUpscaler.Items.AddRange(@('auto','dlss','xess','fsr31','fsr402_external'));$cmbUpscaler.SelectedIndex=0;$tabAdv.Controls.Add($cmbUpscaler)
Label $tabAdv 270 65 'hook'|Out-Null;$cmbHook=New-Object Windows.Forms.ComboBox;$cmbHook.Location='270,90';$cmbHook.Width=210;$cmbHook.DropDownStyle='DropDownList';[void]$cmbHook.Items.AddRange(@('dxgi.dll','winmm.dll','version.dll','dbghelp.dll','d3d12.dll','OptiScaler.asi'));$cmbHook.SelectedIndex=0;$tabAdv.Controls.Add($cmbHook)
Label $tabAdv 510 65 'frame_generation'|Out-Null;$cmbFG=New-Object Windows.Forms.ComboBox;$cmbFG.Location='510,90';$cmbFG.Width=220;$cmbFG.DropDownStyle='DropDownList';[void]$cmbFG.Items.AddRange(@((T 'auto'),(T 'off'),'fsrfg','xefg'));$cmbFG.SelectedIndex=0;$tabAdv.Controls.Add($cmbFG)
$chk402=New-Object Windows.Forms.CheckBox;$chk402.Location='20,150';$chk402.AutoSize=$true;Bind $chk402 'external_402';$tabAdv.Controls.Add($chk402);$txt402=New-Object Windows.Forms.TextBox;$txt402.Location='20,180';$txt402.Width=600;$tabAdv.Controls.Add($txt402);$btn402=New-Object Windows.Forms.Button;$btn402.Location='635,178';$btn402.Size='130,28';Bind $btn402 'select_dll';$tabAdv.Controls.Add($btn402);$lbl402=New-Object Windows.Forms.Label;$lbl402.Location='20,215';$lbl402.Size='745,35';Bind $lbl402 'external_402_note';$tabAdv.Controls.Add($lbl402)
Label $tabAdv 20 280 'ingame_language'|Out-Null;$cmbInGame=New-Object Windows.Forms.ComboBox;$cmbInGame.Location='20,305';$cmbInGame.Width=220;$cmbInGame.DropDownStyle='DropDownList';[void]$cmbInGame.Items.AddRange($localeNames);$cmbInGame.SelectedIndex=$cmbLanguage.SelectedIndex;$tabAdv.Controls.Add($cmbInGame);$lblInGame=New-Object Windows.Forms.Label;$lblInGame.Location='260,305';$lblInGame.Size='500,50';Bind $lblInGame 'ingame_note';$tabAdv.Controls.Add($lblInGame)
Label $tabSupport 20 20 'privacy_title'|Out-Null;$lblPrivacy=New-Object Windows.Forms.Label;$lblPrivacy.Location='20,50';$lblPrivacy.Size='760,85';Bind $lblPrivacy 'privacy_note';$tabSupport.Controls.Add($lblPrivacy);$btnExport=New-Object Windows.Forms.Button;$btnExport.Location='20,160';$btnExport.Size='230,55';Bind $btnExport 'export_support';$tabSupport.Controls.Add($btnExport);$btnReport=New-Object Windows.Forms.Button;$btnReport.Location='270,160';$btnReport.Size='230,55';Bind $btnReport 'prepare_github';$tabSupport.Controls.Add($btnReport);$btnOpen=New-Object Windows.Forms.Button;$btnOpen.Location='520,160';$btnOpen.Size='230,55';Bind $btnOpen 'open_reports';$tabSupport.Controls.Add($btnOpen);$btnPrivacy=New-Object Windows.Forms.Button;$btnPrivacy.Location='20,245';$btnPrivacy.Size='230,40';Bind $btnPrivacy 'open_privacy';$tabSupport.Controls.Add($btnPrivacy);$btnCompat=New-Object Windows.Forms.Button;$btnCompat.Location='270,245';$btnCompat.Size='230,40';Bind $btnCompat 'open_compat';$tabSupport.Controls.Add($btnCompat)
$status=New-Object Windows.Forms.Label;$status.Location='20,620';$status.Size='820,30';$status.Text=T 'ready';$form.Controls.Add($status)
$btnBrowse.Add_Click({$d=New-Object Windows.Forms.FolderBrowserDialog;if($d.ShowDialog()-eq'OK'){$txtFolder.Text=$d.SelectedPath}});$btn402.Add_Click({$d=New-Object Windows.Forms.OpenFileDialog;$d.Filter='DLL (*.dll)|*.dll';if($d.ShowDialog()-eq'OK'){$txt402.Text=$d.FileName}})
$numFps.Add_ValueChanged({RefreshRecommendation});$cmbStrategy.Add_SelectedIndexChanged({RefreshRecommendation});$cmbLanguage.Add_SelectedIndexChanged({ApplyLanguage});$cmbInGame.Add_SelectedIndexChanged({})
function DoSupport{& (Join-Path $Root 'Tools\Collect-Diagnostics.ps1') -GameFolder $txtFolder.Text -Locale $script:Locale -OpenFolder|Out-Null;$status.Text=T 'support_done'}
$btnExport.Add_Click({DoSupport});$btnSupportQuick.Add_Click({DoSupport});$btnReport.Add_Click({& (Join-Path $Root 'Tools\Prepare-GitHub-Report.ps1') -OpenBrowser;$status.Text=T 'report_ready'});$btnOpen.Add_Click({Start-Process 'https://github.com/ORIGNALBLUE/2026-endgames-v1.0/issues/new?template=lifeline-report.yml'});$btnPrivacy.Add_Click({Start-Process (Join-Path $Root 'Docs\PRIVACY_ZH-TW_EN.md')});$btnCompat.Add_Click({Start-Process (Join-Path $Root 'Docs\Compatibility_Tiers_ZH-TW_EN.md')})
$btnRestore.Add_Click({if(Restore $txtFolder.Text){$status.Text=T 'status_restored'}})
$btnApply.Add_Click({$folder=$txtFolder.Text.Trim();if(!(Test-Path $folder)){$status.Text=T 'invalid_folder';return};if(AntiCheat $folder){$status.Text=T 'anticheat_block';return};$rec=Recommendation;$u=if($cmbUpscaler.SelectedItem -eq 'auto'){$rec.Upscaler}else{[string]$cmbUpscaler.SelectedItem};$fgout=$rec.FG;if($cmbFG.SelectedIndex -eq 1){$fgout='nofg'}elseif($cmbFG.SelectedIndex -eq 2){$fgout='fsrfg'}elseif($cmbFG.SelectedIndex -eq 3){$fgout='xefg'};if([int]$numFps.Value-lt30){$fgout='nofg'};$copy=CopyBaseline $folder ([string]$cmbHook.SelectedItem);$ini=$copy.Ini;SetIni $ini 'Inputs' 'EnableDlssInputs' 'true';SetIni $ini 'Inputs' 'EnableXeSSInputs' 'true';SetIni $ini 'Inputs' 'EnableFsr2Inputs' 'true';SetIni $ini 'Inputs' 'EnableFsr3Inputs' 'true';SetIni $ini 'Inputs' 'EnableFfxInputs' 'true';if($u-eq'fsr402_external'){if(!$chk402.Checked){$status.Text=T 'fsr402_missing';return};$v=Validate402 $txt402.Text;if(!$v.Ok){$status.Text=$v.Why;return};Copy-Item $txt402.Text (Join-Path $folder 'amd_fidelityfx_upscaler_dx12.dll') -Force;SetIni $ini 'Upscalers' 'Dx12Upscaler' 'ffx';SetIni $ini 'FSR' 'Fsr4Update' 'true';SetIni $ini 'FSR' 'Fsr4ForceEnableInt8' 'true';Log ('External FSR402: '+$v.Why)}else{SetIni $ini 'Upscalers' 'Dx12Upscaler' $u;SetIni $ini 'Upscalers' 'Dx11Upscaler' $u;SetIni $ini 'Upscalers' 'VulkanUpscaler' $u};SetIni $ini 'FrameGen' 'Enabled' ($(if($fgout-ne'nofg'){'true'}else{'false'}));SetIni $ini 'FrameGen' 'FGOutput' $fgout;SetIni $ini 'Menu' 'OverlayMenu' 'true';SetIni $ini 'Log' 'LogToFile' 'true';SetIni $ini 'Log' 'LogLevel' '2';$ig=$localeCodes[$cmbInGame.SelectedIndex];Set-Content (Join-Path $folder 'LifelineLanguage.txt') -Value $ig -Encoding ASCII;$font=FontForLocale $ig;if($font){SetIni $ini 'Menu' 'TTFFontPath' $font};Log ("GPU=$($gpu.Name);tier=$($tier.id);up=$u;fg=$fgout;basefps=$($numFps.Value);vram=$($gpu.VRAM);locale=$script:Locale;ingame=$ig");$status.Text=(T 'status_applied')+' — '+$u+' + '+$fgout})
RefreshRecommendation
[void]$form.ShowDialog()
