#requires -version 5.1
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()
$Root=Split-Path -Parent $MyInvocation.MyCommand.Path
$Runtime=Join-Path $Root 'Runtime'
$Profiles=Get-Content (Join-Path $Root 'Profiles\legacy_profiles.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$LogDir=Join-Path $Root 'Logs';New-Item -ItemType Directory -Force -Path $LogDir|Out-Null
$Log=Join-Path $LogDir ('Lifeline-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'.log')
function Log($m){Add-Content -LiteralPath $Log -Encoding UTF8 -Value ((Get-Date -Format 's')+' '+$m)}
function GpuInfo{try{$g=Get-CimInstance Win32_VideoController|Select-Object -First 1 Name,AdapterRAM,DriverVersion;$v=if($g.AdapterRAM){[math]::Round($g.AdapterRAM/1GB,1)}else{0};[pscustomobject]@{Name=$g.Name;VRAM=$v;Driver=$g.DriverVersion}}catch{[pscustomobject]@{Name='Unknown';VRAM=0;Driver='Unknown'}}}
function Tier($name){foreach($t in $Profiles.tiers){foreach($m in $t.match){if($name -like ('*'+$m+'*')){return $t}}};return ($Profiles.tiers|Where-Object id -eq 'OTHER')}
function SetIni($path,$sec,$key,$val){if(!(Test-Path $path)){return};$a=[System.Collections.Generic.List[string]](Get-Content $path);$s='['+$sec+']';$si=-1;$next=$a.Count;for($i=0;$i -lt $a.Count;$i++){if($a[$i].Trim() -ieq $s){$si=$i;break}};if($si -lt 0){$a.Add('');$a.Add($s);$a.Add($key+'='+$val);Set-Content $path $a -Encoding UTF8;return};for($i=$si+1;$i -lt $a.Count;$i++){if($a[$i]-match '^\s*\['){$next=$i;break}};for($i=$si+1;$i -lt $next;$i++){if($a[$i]-match ('^\s*'+[regex]::Escape($key)+'\s*=')){$a[$i]=$key+'='+$val;Set-Content $path $a -Encoding UTF8;return}};$a.Insert($next,$key+'='+$val);Set-Content $path $a -Encoding UTF8}
function AntiCheat($folder){foreach($m in @('EasyAntiCheat','BattlEye','vgk','xigncode','nProtect')){if(Get-ChildItem $folder -Recurse -Force -ErrorAction SilentlyContinue|Where-Object Name -like ('*'+$m+'*')|Select-Object -First 1){return $true}};return $false}
function Validate402($file){if(!(Test-Path $file)){return [pscustomobject]@{Ok=$false;Why='Missing file'}};if($file -match '(?i)4\.0\.2c|402c'){return [pscustomobject]@{Ok=$false;Why='FSR 4.0.2c is explicitly blocked'}};$v=(Get-Item $file).VersionInfo.FileVersion;if($v -and $v -notmatch '^4\.0\.2'){return [pscustomobject]@{Ok=$false;Why=('Version is not 4.0.2: '+$v)}};$sig=Get-AuthenticodeSignature $file;return [pscustomobject]@{Ok=$true;Why=('4.0.2 candidate; signature='+$sig.Status+'; version='+$v)}}
function CopyBaseline($folder,$hook){$backup=Join-Path $folder ('.AetherScaler_Lifeline_Backup\'+(Get-Date -Format 'yyyyMMdd-HHmmss'));New-Item -ItemType Directory -Force -Path $backup|Out-Null;foreach($n in @($hook,'OptiScaler.ini','amd_fidelityfx_dx12.dll','amd_fidelityfx_upscaler_dx12.dll','amd_fidelityfx_framegeneration_dx12.dll','fakenvapi.dll','fakenvapi.ini','libxess.dll','libxess_fg.dll','libxell.dll')){if(Test-Path (Join-Path $folder $n)){Copy-Item (Join-Path $folder $n) $backup -Force}};Copy-Item (Join-Path $Runtime 'OptiScaler.dll') (Join-Path $folder $hook) -Force;$ini=Join-Path $folder 'OptiScaler.ini';if(!(Test-Path $ini)){Copy-Item (Join-Path $Runtime 'OptiScaler.ini.template') $ini -Force};foreach($n in @('amd_fidelityfx_dx12.dll','amd_fidelityfx_upscaler_dx12.dll','amd_fidelityfx_framegeneration_dx12.dll','amd_fidelityfx_vk.dll','fakenvapi.dll','fakenvapi.ini','libxess.dll','libxess_dx11.dll','libxess_fg.dll','libxell.dll','dlssg_to_fsr3_amd_is_better.dll')){if(Test-Path (Join-Path $Runtime $n)){Copy-Item (Join-Path $Runtime $n) $folder -Force}};return $ini}
$gpu=GpuInfo;$tier=Tier $gpu.Name
$form=New-Object Windows.Forms.Form;$form.Text='AetherScaler Lifeline 0.1 / 續命版';$form.Size='850,650';$form.StartPosition='CenterScreen'
function L($x,$y,$txt){$o=New-Object Windows.Forms.Label;$o.Location="$x,$y";$o.AutoSize=$true;$o.Text=$txt;$form.Controls.Add($o);$o}
function C($x,$y,$w,$items,$idx){$o=New-Object Windows.Forms.ComboBox;$o.Location="$x,$y";$o.Width=$w;$o.DropDownStyle='DropDownList';[void]$o.Items.AddRange($items);$o.SelectedIndex=$idx;$form.Controls.Add($o);$o}
L 20 20 'Game folder / 遊戲資料夾'|Out-Null;$path=New-Object Windows.Forms.TextBox;$path.Location='20,45';$path.Width=620;$form.Controls.Add($path)
$browse=New-Object Windows.Forms.Button;$browse.Location='655,43';$browse.Size='145,28';$browse.Text='Browse / 瀏覽';$browse.Add_Click({$d=New-Object Windows.Forms.FolderBrowserDialog;if($d.ShowDialog()-eq 'OK'){$path.Text=$d.SelectedPath}});$form.Controls.Add($browse)
$info=L 20 88 ("GPU: {0} | VRAM: {1} GB | Driver: {2}`nTier: {3}" -f $gpu.Name,$gpu.VRAM,$gpu.Driver,$tier.label);$info.Size='770,45'
L 20 145 'Rescue profile / 續命策略'|Out-Null;$mode=C 20 170 230 @('Conservative / 保守','Balanced / 平衡','Aggressive / 激進') 1
L 280 145 'Primary upscaler / 主升頻器'|Out-Null;$up=C 280 170 230 @('dlss','xess','fsr31','fsr402_external') 0;$up.SelectedItem=$tier.primary
L 540 145 'Hook'|Out-Null;$hook=C 540 170 200 @('dxgi.dll','winmm.dll','version.dll','dbghelp.dll','d3d12.dll','OptiScaler.asi') 0
L 20 220 'Measured pre-FG FPS / 實測 FG 前 FPS'|Out-Null;$fps=New-Object Windows.Forms.NumericUpDown;$fps.Location='20,245';$fps.Minimum=1;$fps.Maximum=300;$fps.Value=45;$form.Controls.Add($fps)
L 280 220 'Frame Generation / 畫格生成'|Out-Null;$fg=C 280 245 230 @('auto','off','fsrfg','xefg') 0
$warn=L 20 295 '';$warn.Size='770,70';$warn.ForeColor=[Drawing.Color]::DarkOrange
$ext=New-Object Windows.Forms.CheckBox;$ext.Location='20,375';$ext.AutoSize=$true;$ext.Text='Use external FSR 4.0.2 / 使用外部 FSR 4.0.2（不含 4.0.2c）';$form.Controls.Add($ext)
$extPath=New-Object Windows.Forms.TextBox;$extPath.Location='20,405';$extPath.Width=620;$form.Controls.Add($extPath)
$extBrowse=New-Object Windows.Forms.Button;$extBrowse.Location='655,403';$extBrowse.Size='145,28';$extBrowse.Text='Select DLL';$extBrowse.Add_Click({$d=New-Object Windows.Forms.OpenFileDialog;$d.Filter='DLL (*.dll)|*.dll';if($d.ShowDialog()-eq 'OK'){$extPath.Text=$d.FileName}});$form.Controls.Add($extBrowse)
$apply=New-Object Windows.Forms.Button;$apply.Location='20,475';$apply.Size='250,55';$apply.Text='Apply Lifeline / 套用續命設定';$form.Controls.Add($apply)
$status=L 20 550 'Ready / 就緒';$status.Size='770,30'
function RefreshWarn{$f=[int]$fps.Value;if($f -lt 30){$txt='FG BLOCKED: base FPS < 30. Upscaling only. / 基礎 FPS 低於 30，禁止 FG。'}elseif($f -lt 40){$txt='Upscaling first. FG is not recommended. / 先救基礎幀率，不建議 FG。'}elseif($f -lt [int]$tier.min_fg_fps){$txt='Experimental FG range. / FG 實驗區間。'}else{$txt='FG may be enabled; stable frame pacing remains priority. / 可啟用 FG，但優先穩定幀時間。'};if($gpu.VRAM -lt 6){$txt+='  VRAM < 6 GB: keep FG off if stutter appears.'};$warn.Text=$txt}
$fps.Add_ValueChanged({RefreshWarn});RefreshWarn
$apply.Add_Click({$folder=$path.Text.Trim();if(!(Test-Path $folder)){$status.Text='Invalid game folder';return};if(AntiCheat $folder){$status.Text='Blocked: anti-cheat detected';return};$chosen=[string]$up.SelectedItem;$fgout='nofg';$f=[int]$fps.Value;if($fg.SelectedItem -eq 'fsrfg'){$fgout='fsrfg'}elseif($fg.SelectedItem -eq 'xefg'){$fgout='xefg'}elseif($fg.SelectedItem -eq 'auto' -and $f -ge [int]$tier.min_fg_fps){$fgout=[string]$tier.fg};if($f -lt 30 -or $mode.SelectedIndex -eq 0){$fgout='nofg'};$ini=CopyBaseline $folder ([string]$hook.SelectedItem);SetIni $ini 'Inputs' 'EnableDlssInputs' 'true';SetIni $ini 'Inputs' 'EnableXeSSInputs' 'true';SetIni $ini 'Inputs' 'EnableFsr2Inputs' 'true';SetIni $ini 'Inputs' 'EnableFsr3Inputs' 'true';SetIni $ini 'Inputs' 'EnableFfxInputs' 'true';if($chosen -eq 'fsr402_external'){if(!$ext.Checked){$status.Text='External FSR 4.0.2 not enabled';return};$v=Validate402 $extPath.Text;if(!$v.Ok){$status.Text=$v.Why;return};Copy-Item $extPath.Text (Join-Path $folder 'amd_fidelityfx_upscaler_dx12.dll') -Force;SetIni $ini 'Upscalers' 'Dx12Upscaler' 'fsr31';SetIni $ini 'FSR' 'Fsr4Update' 'true';SetIni $ini 'FSR' 'Fsr4ForceEnableInt8' 'true';Log ('External FSR402: '+$v.Why)}else{SetIni $ini 'Upscalers' 'Dx12Upscaler' $chosen};SetIni $ini 'FrameGen' 'Enabled' ($(if($fgout-ne'nofg'){'true'}else{'false'}));SetIni $ini 'FrameGen' 'FGOutput' $fgout;SetIni $ini 'Log' 'LogToFile' 'true';SetIni $ini 'Log' 'LogLevel' '2';Log ("GPU=$($gpu.Name);tier=$($tier.id);up=$chosen;fg=$fgout;basefps=$f;vram=$($gpu.VRAM)");$status.Text='Applied / 已套用 — '+$chosen+' + '+$fgout})
[void]$form.ShowDialog()
