param([string]$GameFolder='',[string]$OutputDirectory='',[string]$Locale='en-US',[switch]$OpenFolder)
$ErrorActionPreference='SilentlyContinue';$Root=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path);if(!$OutputDirectory){$OutputDirectory=Join-Path $Root 'SupportBundles'};New-Item -ItemType Directory -Force -Path $OutputDirectory|Out-Null;$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$work=Join-Path $env:TEMP "AetherScalerSupport-$stamp";New-Item -ItemType Directory -Force -Path $work|Out-Null
function Redact([string]$s){if($null-eq$s){return''};foreach($v in @($env:USERNAME,$env:USERPROFILE,$env:COMPUTERNAME,$GameFolder)){if($v){$s=$s-replace[regex]::Escape($v),'<REDACTED>'}};$s=$s-replace '(?i)\b(?:\d{1,3}\.){3}\d{1,3}\b','<IP>';$s=$s-replace '(?i)\b(?:[0-9A-F]{2}[:-]){5}[0-9A-F]{2}\b','<MAC>';return $s}
function CopyText($src,$dst){if(Test-Path $src){$t=Get-Content $src -Raw -ErrorAction SilentlyContinue;if($null-ne$t){Set-Content $dst (Redact $t) -Encoding UTF8}}}
function VramBucket($b){if(!$b){return'unknown'};$g=$b/1GB;if($g-lt5){return'<5GB'}elseif($g-lt7){return'5-6GB'}elseif($g-lt10){return'7-9GB'}elseif($g-lt14){return'10-13GB'}elseif($g-lt20){return'14-19GB'}else{return'20GB+'}}
function IniValue($p,$sec,$key){if(!(Test-Path $p)){return''};$in=$false;foreach($l in Get-Content $p){if($l.Trim()-ieq('['+$sec+']')){$in=$true;continue};if($in-and$l-match'^\s*\['){break};if($in-and$l-match('^\s*'+[regex]::Escape($key)+'\s*=\s*(.*)$')){return $matches[1].Trim()}}return''}
function VersionRow($p){if(!(Test-Path $p)){return$null};$i=Get-Item $p;[pscustomobject]@{name=$i.Name;version=$i.VersionInfo.FileVersion;sha256=(Get-FileHash $p -Algorithm SHA256).Hash}}
$gpu=Get-CimInstance Win32_VideoController|Select-Object -First 1;$os=Get-CimInstance Win32_OperatingSystem;$ini=if($GameFolder){Join-Path $GameFolder 'OptiScaler.ini'}else{''};$runtime=@();if($GameFolder-and(Test-Path $GameFolder)){foreach($n in @('dxgi.dll','winmm.dll','version.dll','dbghelp.dll','d3d12.dll','OptiScaler.asi','libxess.dll','libxess_fg.dll','libxell.dll','fakenvapi.dll','amd_fidelityfx_upscaler_dx12.dll','amd_fidelityfx_framegeneration_dx12.dll')){$r=VersionRow (Join-Path $GameFolder $n);if($r){$runtime+=$r}}}
$pub=[ordered]@{schema=2;report_id=[guid]::NewGuid().ToString();generated_at=(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ');lifeline_version='0.2.0';locale=$Locale;gpu=$gpu.Name;driver=$gpu.DriverVersion;vram_bucket=(VramBucket $gpu.AdapterRAM);os=($os.Caption+' '+$os.BuildNumber);tier='auto-detect';api='unknown';upscaler=$(IniValue $ini 'Upscalers' 'Dx12Upscaler');frame_generation=$(IniValue $ini 'FrameGen' 'FGOutput');runtime_versions=$runtime;result='not-specified'}
$pubPath=Join-Path $OutputDirectory "PublicSummary_$stamp.json";$pub|ConvertTo-Json -Depth 6|Set-Content $pubPath -Encoding UTF8
$private=Join-Path $work 'private';New-Item -ItemType Directory -Force -Path $private|Out-Null;$sys=[ordered]@{generated_at=$pub.generated_at;lifeline_version='0.2.0';os=[ordered]@{caption=$os.Caption;version=$os.Version;build=$os.BuildNumber;architecture=$os.OSArchitecture;locale=$os.Locale};gpu=[ordered]@{name=$gpu.Name;driver=$gpu.DriverVersion;vram_bucket=$pub.vram_bucket};game_folder=$(if($GameFolder){'<REDACTED>'}else{'not selected'})};$sys|ConvertTo-Json -Depth 5|Set-Content (Join-Path $private 'system.json') -Encoding UTF8
foreach($n in @('sdk_tracker.json','sdk_manifest.json','lifeline_settings.json','reporting.json')){CopyText (Join-Path $Root $n) (Join-Path $private $n)};$logs=Join-Path $private 'logs';New-Item -ItemType Directory -Force -Path $logs|Out-Null;if(Test-Path(Join-Path $Root 'Logs')){Get-ChildItem (Join-Path $Root 'Logs') -File|Sort LastWriteTime -Descending|Select -First 5|%{CopyText $_.FullName (Join-Path $logs $_.Name)}};if($GameFolder-and(Test-Path $GameFolder)){foreach($n in @('OptiScaler.log','fakenvapi.log','dlssg_to_fsr3.log','OptiScaler.ini','LifelineLanguage.txt')){CopyText (Join-Path $GameFolder $n) (Join-Path $logs $n)};$runtime|ConvertTo-Json -Depth 4|Set-Content (Join-Path $private 'runtime_hashes.json') -Encoding UTF8}
@'
AetherScaler Lifeline Private Support Bundle
This ZIP is created locally and is never uploaded automatically.
Text paths, user/computer names, IPv4 and MAC-like strings are redacted.
Review before sharing.
'@ | Set-Content (Join-Path $private 'README_PRIVACY.txt') -Encoding UTF8
$zip=Join-Path $OutputDirectory "PrivateSupport_$stamp.zip";Compress-Archive -Path (Join-Path $private '*') -DestinationPath $zip -Force;Remove-Item $work -Recurse -Force;Write-Output $pubPath;Write-Output $zip;if($OpenFolder){Start-Process explorer.exe -ArgumentList "/select,`"$pubPath`""}
